// Code generated by mockery v1.0.0. DO NOT EDIT.

package automock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	v1 "k8s.io/api/networking/v1"
)

// NetworkPoliciesProvider is an autogenerated mock type for the NetworkPoliciesProvider type
type NetworkPoliciesProvider struct {
	mock.Mock
}

// GetNetworkPoliciesForNamespace provides a mock function with given fields: ctx, ns
func (_m *NetworkPoliciesProvider) GetNetworkPoliciesForNamespace(ctx context.Context, ns string) ([]v1.NetworkPolicy, error) {
	ret := _m.Called(ctx, ns)

	var r0 []v1.NetworkPolicy
	if rf, ok := ret.Get(0).(func(context.Context, string) []v1.NetworkPolicy); ok {
		r0 = rf(ctx, ns)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]v1.NetworkPolicy)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, ns)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
